"""
swarm_mission.launch.py — Launch 4-drone swarm mission for full field coverage.

Starts:
  1. task_allocator  — divides field_grid.json into sectors, assigns cells to drones
  2. swarm_agent[0]  — drone_0, home pad NED(-6, -6)
  3. swarm_agent[1]  — drone_1, home pad NED(-6,  6)
  4. swarm_agent[2]  — drone_2, home pad NED( 6, -6)
  5. swarm_agent[3]  — drone_3, home pad NED( 6,  6)

Prerequisites (must be running before this launch):
  - PX4 SITL instances 0..3 (swarm_field world, matching Gazebo model)
  - MicroXRCE-DDS bridge (port 8888)
  - perimeters/field_grid.json  generated by grid_generator_sim

Parameters (override via launch args):
  drone_count     int    4       number of drones (must match running SITL instances)
  ready_timeout   float  30.0   seconds to wait for READY before starting mission
  altitude_m      float  5.0    cruise altitude above ground [m]
  cruise_speed    float  2.0    horizontal cruise speed [m/s]
  hover_secs      float  1.0    hover time at each cell centre [s]

Usage:
  ros2 launch scout_control swarm_mission.launch.py
  ros2 launch scout_control swarm_mission.launch.py altitude_m:=8.0 cruise_speed:=3.0
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:

    # ── Launch arguments ──────────────────────────────────────────────────────
    args = [
        DeclareLaunchArgument("drone_count",   default_value="4",
                              description="Number of drone SITL instances"),
        DeclareLaunchArgument("ready_timeout", default_value="30.0",
                              description="Seconds to wait for all READY before starting"),
        DeclareLaunchArgument("altitude_m",    default_value="5.0",
                              description="Cruise altitude above ground [m]"),
        DeclareLaunchArgument("cruise_speed",  default_value="2.0",
                              description="Horizontal cruise speed [m/s]"),
    ]

    drone_count   = LaunchConfiguration("drone_count")
    ready_timeout = LaunchConfiguration("ready_timeout")
    altitude_m    = LaunchConfiguration("altitude_m")
    cruise_speed  = LaunchConfiguration("cruise_speed")

    # ── Nodes ─────────────────────────────────────────────────────────────────

    # Task allocator — ground station orchestrator
    task_allocator_node = Node(
        package="scout_control",
        executable="task_allocator",
        name="task_allocator",
        output="screen",
        parameters=[{
            "drone_count":   drone_count,
            "ready_timeout": ready_timeout,
        }],
    )

    home_pads_ned = [
        (-6.0, -6.0),  # landing_pad_0: Gz ENU(-6, -6)
        (-6.0,  6.0),  # landing_pad_1: Gz ENU( 6, -6)
        ( 6.0, -6.0),  # landing_pad_2: Gz ENU(-6,  6)
        ( 6.0,  6.0),  # landing_pad_3: Gz ENU( 6,  6)
    ]

    swarm_agents = [
        Node(
            package="scout_control",
            executable="swarm_agent",
            name=f"swarm_agent_{drone_id}",
            output="screen",
            parameters=[{
                "drone_id":     drone_id,
                "altitude_m":   altitude_m,
                "home_ned_x":   home_x,
                "home_ned_y":   home_y,
                "cruise_speed": cruise_speed,
            }],
        )
        for drone_id, (home_x, home_y) in enumerate(home_pads_ned)
    ]

    return LaunchDescription(args + [
        task_allocator_node,
        *swarm_agents,
    ])
