"""
swarm_mission.launch.py — Launch 2-drone swarm mission for full field coverage.

Starts:
  1. task_allocator  — divides field_grid.json into sectors, assigns cells to drones
  2. swarm_agent[0]  — drone_0, home pad NED(0, 0)
  3. swarm_agent[1]  — drone_1, home pad NED(0, -3)

Prerequisites (must be running before this launch):
  - PX4 SITL instance 0  (swarm_field world, gz_x500_mono_cam model)
  - PX4 SITL instance 1  (PX4_GZ_STANDALONE=1, same world)
  - MicroXRCE-DDS bridge (port 8888)
  - perimeters/field_grid.json  generated by grid_generator_sim

Parameters (override via launch args):
  drone_count     int    2       number of drones (must match running SITL instances)
  ready_timeout   float  30.0   seconds to wait for READY before starting mission
  altitude_m      float  5.0    cruise altitude above ground [m]
  cruise_speed    float  2.0    horizontal cruise speed [m/s]
  hover_secs      float  1.0    hover time at each cell centre [s]
  home_ned_y_1    float  -3.0   drone_1 home pad NED y (must match swarm_field.sdf)

Usage:
  ros2 launch scout_control swarm_mission.launch.py
  ros2 launch scout_control swarm_mission.launch.py altitude_m:=8.0 cruise_speed:=3.0
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:

    # ── Launch arguments ──────────────────────────────────────────────────────
    args = [
        DeclareLaunchArgument("drone_count",   default_value="2",
                              description="Number of drone SITL instances"),
        DeclareLaunchArgument("ready_timeout", default_value="30.0",
                              description="Seconds to wait for all READY before starting"),
        DeclareLaunchArgument("altitude_m",    default_value="5.0",
                              description="Cruise altitude above ground [m]"),
        DeclareLaunchArgument("cruise_speed",  default_value="2.0",
                              description="Horizontal cruise speed [m/s]"),
        DeclareLaunchArgument("home_ned_y_1",  default_value="3.0",
                              description="drone_1 home pad NED y [m] (pad_1 is east of pad_0)"),
    ]

    drone_count   = LaunchConfiguration("drone_count")
    ready_timeout = LaunchConfiguration("ready_timeout")
    altitude_m    = LaunchConfiguration("altitude_m")
    cruise_speed  = LaunchConfiguration("cruise_speed")
    home_ned_y_1  = LaunchConfiguration("home_ned_y_1")

    # ── Nodes ─────────────────────────────────────────────────────────────────

    # Task allocator — ground station orchestrator
    task_allocator_node = Node(
        package="scout_control",
        executable="task_allocator",
        name="task_allocator",
        output="screen",
        parameters=[{
            "drone_count":   drone_count,
            "ready_timeout": ready_timeout,
        }],
    )

    # Drone 0 — bare PX4 namespace, home pad NED(0, 0)
    swarm_agent_0 = Node(
        package="scout_control",
        executable="swarm_agent",
        name="swarm_agent_0",
        output="screen",
        parameters=[{
            "drone_id":     0,
            "altitude_m":   altitude_m,
            "home_ned_x":   0.0,
            "home_ned_y":   0.0,
            "cruise_speed": cruise_speed,
        }],
    )

    # Drone 1 — /px4_1/ namespace, home pad NED(0, home_ned_y_1)
    swarm_agent_1 = Node(
        package="scout_control",
        executable="swarm_agent",
        name="swarm_agent_1",
        output="screen",
        parameters=[{
            "drone_id":     1,
            "altitude_m":   altitude_m,
            "home_ned_x":   0.0,
            "home_ned_y":   home_ned_y_1,
            "cruise_speed": cruise_speed,
        }],
    )

    return LaunchDescription(args + [
        task_allocator_node,
        swarm_agent_0,
        swarm_agent_1,
    ])
